- roadmap.md
> Add roadmap for app development

- roadmap.md
> Add omitted map mentions

- __tests__/AdPage.test.ts
- __tests__/Screen.test.ts
- __tests__/ScrollPage.test.ts
- __tests__/ShelterPage.test.ts
- __tests__/types.d.ts
> Add middleScreen interfaces with tests

- .eslintrc.js
- .github/pull_request_template.md
- .github/workflows/lint.yaml
- __tests__/AdPage.test.ts
- __tests__/PermissionsList.test.ts
- __tests__/Shelter.test.ts
- __tests__/ShelterPage.test.ts
- __tests__/StartingScreen.test.ts
- package.json
- prettier.config.js
- roadmap.md
- yarn.lock
> Add plan for next sprint and static analysis!

- __tests__/AdFilters.test.ts
- __tests__/AppSettings.test.ts
- __tests__/PreferencesScreen.test.ts
- __tests__/types.d.ts
> Add tests for AppSettings and AdFilters

- MeowdoptMeApp/src/PreferencesScreen.tsx
> PreferencesScreen added

- .github/workflows/backend-formatting.yaml
- BackendApp/BackendApp/settings.py
- BackendApp/Makefile
- BackendApp/initial_data.py
- BackendApp/manage.py
- BackendApp/userAuth/apps.py
- BackendApp/userAuth/models.py
- BackendApp/userAuth/serializers.py
- BackendApp/userAuth/tests.py
- BackendApp/userAuth/urls.py
- BackendApp/userAuth/views.py
We have some issues with Python formatting. No more.
> [CI] Add python formatting test and tools

- .github/workflows/backend-testing.yaml
- BackendApp/userAuth/tests.py
add workflow backend-testing
:rocket:
> [CI] Add python django testing in BackendApp and tools

- MeowdoptMeApp/assets/colors.json
- MeowdoptMeApp/assets/colors.ts
- MeowdoptMeApp/src/StartingScreen.tsx
- MeowdoptMeApp/src/components/GeneralButton.tsx
- MeowdoptMeApp/src/components/Status.tsx
> Move status indicator to separate component

- MeowdoptMeApp/src/Database.ts
- MeowdoptMeApp/src/authUtils.ts
> Fix frontend usage of endpoints

- BackendApp/test_guide.md
Rewriting test_guide to form that I'm using in app.
:rocket:
> [backend] Edit test_guide.md

- BackendApp/adRelated/tests.py
- BackendApp/shelterRelated/tests.py
- BackendApp/userAuth/tests.py
Removing APIRequestFactory objects from tests, cleaning unused imports
:rocket:
> [backend] Tests refactoring

- BackendApp/userAuth/serializers.py
- BackendApp/userAuth/utils.py
- BackendApp/userAuth/views.py
Add response cases in userAuth part
error: The user with the provided email address does not exist
error: There was a problem decoding the provided uidb64 code.
:rocket:
> [backend] Add error response

- BackendApp/adRelated/filters.py
- BackendApp/adRelated/models.py
- BackendApp/adRelated/serializers.py
- BackendApp/adRelated/tests.py
- BackendApp/initial_data/ads.json
- BackendApp/initial_data/init.py
- BackendApp/photoAlbum/permissions.py
- BackendApp/photoAlbum/tests.py
fix json accoring to out diagram :)))
change from this:
result: 
Related elements on diagram:
:rocket:
> [backend] Fix request json in adRelated

- BackendApp/initial_data/photo_albums.json
- BackendApp/photoAlbum/views.py
1. png to jpg 
2. if photo album contains only 5 elements, only them can be returned
before:
after:
:rocket:
> [backend] Fix photoAlbum files

- BackendApp/BackendApp/settings.py
> Fix time on backend

- BackendApp/adRelated/views.py
- BackendApp/initial_data/init.py
- BackendApp/initial_data/photo_albums.json
- BackendApp/photoAlbum/models.py
- BackendApp/photoAlbum/serializers.py
- BackendApp/photoAlbum/tests.py
- BackendApp/photoAlbum/utils.py
Fix and add requested changes
1. After post request on ads/add/ you can get id from new ad
2. Remove "name" from making PhotoAlbum 
:rocket:
> [backend] Fix adRelated part

- BackendApp/initial_data/user_permissions.json
- BackendApp/initial_data/utils.py
> [backend] Permissions for admin in initial data and func for creating admin user

- BackendApp/README.md
- BackendApp/adRelated/filters.py
- BackendApp/adRelated/serializers.py
- BackendApp/routeProject.md
- BackendApp/shelterRelated/models.py
1. Add requested field for shelter (for displaying "fake ad in the app")
2. Add filter by shelter to ads (ex. `/ads/?shelter=1`)
3. Edit readme according to host backend on `https://gochad.pythonanywhere.com/` (for demo).
4. Edit project endpoints description  
5. Add id for get ad
:rocket:
> [backend] Add field in shelter, filter in ads

- BackendApp/adRelated/serializers.py
- BackendApp/adRelated/tests.py
- BackendApp/photoAlbum/models.py
- BackendApp/photoAlbum/serializers.py
> [backend] Fix put ad

- BackendApp/adRelated/serializers.py
- BackendApp/photoAlbum/permissions.py
- BackendApp/photoAlbum/serializers.py
- BackendApp/photoAlbum/utils.py
- BackendApp/photoAlbum/views.py
Fix put ad in proper way
:rocket:
> [backend] Fix putting ad (again) and convert any image to jpg

- BackendApp/initial_data/init.py
> [backend] Fix add photoAlbum pk to shelter

- BackendApp/userAuth/views.py
> [backend] Add id for response data after login

- BackendApp/photoAlbum/serializers.py
- BackendApp/photoAlbum/views.py
After posting new photo to album you can get response with these fields:
Changes in database after make post
:rocket:
> [backend] Fix adding photo album object to new photo
